/**
 * src/features/mock-interview/services/interviewService.js
 * Real-time Service Layer executing strictly live Spring Boot backend API calls (/api/interviews).
 */

import {
  startInterviewApi,
  getNextQuestionApi,
  submitAnswerApi,
  getSessionDetailsApi,
  getUserHistoryApi,
  getInterviewReportApi,
  deleteSessionApi,
} from "../../../api/interviewApi";
import { INTERVIEW_TRACKS } from "../constants/interviewData";

export const interviewService = {
  /**
   * Start a new AI Mock Interview session
   * POST /api/interviews/start
   */
  async startInterview(setupConfig) {
    const trackId = setupConfig.trackId || "java-fullstack";
    const trackObj = INTERVIEW_TRACKS.find((t) => t.id === trackId) || INTERVIEW_TRACKS[0];
    const difficulty = String(setupConfig.difficulty || "INTERMEDIATE").toUpperCase();
    const questionCount = Number(setupConfig.questionCount || 3);
    const durationMinutes = Number(setupConfig.durationMinutes || 20);

    // Map trackId to backend InterviewTrack enum
    let interviewTrack = "TECHNICAL";
    if (trackId === "system-design") {
      interviewTrack = "SYSTEM_DESIGN";
    } else if (trackId === "behavioral-hr") {
      interviewTrack = "BEHAVIORAL";
    }

    const payload = {
      interviewTrack,
      trackTitle: setupConfig.trackTitle || trackObj.title,
      trackId,
      difficulty,
      interviewType: "TEXT",
      totalQuestions: questionCount,
    };

    const res = await startInterviewApi(payload);
    const apiResponse = res?.data || res;
    const session = apiResponse?.data || apiResponse;
    const sessionId = session?.id || session?.sessionId;

    if (!sessionId) {
      throw new Error("Failed to initialize interview session on backend.");
    }

    // Immediately fetch the first live question generated by the AI backend
    const firstQuestion = await this.getNextQuestion(sessionId);

    return {
      session: {
        ...session,
        trackId,
        trackTitle: payload.trackTitle,
        durationMinutes,
        totalQuestions: questionCount,
        questionCount,
      },
      initialQuestions: firstQuestion ? [firstQuestion] : [],
    };
  },

  /**
   * Fetch Next Question from Spring Boot
   * POST /api/interviews/{sessionId}/next-question
   */
  async getNextQuestion(sessionId) {
    if (!sessionId) return null;
    const res = await getNextQuestionApi(sessionId);
    const apiResponse = res?.data || res;
    const questionData = apiResponse?.data || apiResponse;

    if (!questionData) {
      throw new Error("Failed to retrieve question from backend.");
    }

    return {
      id: questionData.id,
      questionId: questionData.id,
      sessionId: questionData.sessionId || sessionId,
      question: questionData.question,
      questionText: questionData.question,
      difficulty: questionData.difficulty,
      orderNumber: questionData.orderNumber,
      totalQuestions: questionData.totalQuestions,
    };
  },

  /**
   * Submit Answer and Evaluate via AI
   * POST /api/interviews/{sessionId}/submit
   */
  async submitAnswer(sessionId, questionId, answerText) {
    if (!sessionId || questionId === undefined || questionId === null) {
      throw new Error("Session ID and Question ID are required.");
    }

    const sanitizedAnswer = answerText && answerText.trim() ? answerText.trim() : "No answer provided.";

    const payload = {
      questionId: Number(questionId),
      userAnswer: sanitizedAnswer,
    };

    const res = await submitAnswerApi(sessionId, payload);
    const apiResponse = res?.data || res;
    return apiResponse?.data || apiResponse;
  },

  /**
   * Get Complete Interview Report
   * GET /api/interviews/{sessionId}/report
   */
  async getReport(sessionId) {
    if (!sessionId) return null;
    const res = await getInterviewReportApi(sessionId);
    const apiResponse = res?.data || res;
    const report = apiResponse?.data || apiResponse;
    return report;
  },

  /**
   * Get User Interview History (Paginated Page<InterviewSessionResponse>)
   * GET /api/interviews/history
   */
  async getHistory(page = 0, size = 10) {
    const res = await getUserHistoryApi(page, size);
    const apiResponse = res?.data || res;
    const pageData = apiResponse?.data || apiResponse;

    if (pageData?.content && Array.isArray(pageData.content)) {
      return pageData.content;
    }
    if (Array.isArray(pageData)) {
      return pageData;
    }
    return [];
  },

  /**
   * Delete Session
   * DELETE /api/interviews/{sessionId}
   */
  async deleteSession(sessionId) {
    if (!sessionId) return null;
    await deleteSessionApi(sessionId);
    return sessionId;
  },
};
